"""Tests for FastAPI server orchestration."""

from __future__ import annotations

# =============================================================================
# IMPORTS
# =============================================================================
# Standard library
from pathlib import Path

# Third-party
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

# Project/Local
from mock_api.core.constants import HTTPStatus
from mock_api.core.exceptions import SchemaFileNotFoundError
from mock_api.core.server import Server

# =============================================================================
# FIXTURES
# =============================================================================


@pytest.fixture
def models_file() -> str:
    """Path to test models fixture file."""
    return str(Path(__file__).parent / "fixtures" / "generator_models.py")


@pytest.fixture
def server(models_file: str) -> Server:
    """Create a Server instance without data generation."""
    return Server(models_file, generate_data=False)


@pytest.fixture
def server_with_data(models_file: str) -> Server:
    """Create a Server instance with pre-populated data."""
    return Server(models_file, generate_data=True, data_count=10)


@pytest.fixture
def app(server: Server) -> FastAPI:
    """Create FastAPI app from server."""
    return server.create_app()


@pytest.fixture
def client(app: FastAPI) -> TestClient:
    """Create TestClient for API testing."""
    return TestClient(app)


# =============================================================================
# TESTS: Initialization
# =============================================================================


def test_server_initialization(models_file: str) -> None:
    """Test Server initializes correctly."""
    server = Server(models_file)

    assert server.models_file == models_file
    assert server.prefix == "/api/v1"
    assert server.generate_data is False
    assert server.data_count == 10
    assert server.parser is not None
    assert len(server.schemas) > 0
    assert server.store is not None
    assert server.router_generator is not None


def test_server_custom_prefix(models_file: str) -> None:
    """Test Server with custom prefix."""
    server = Server(models_file, prefix="/api/v2")

    assert server.prefix == "/api/v2"
    assert server.router_generator.prefix == "/api/v2"


def test_server_with_data_generation(models_file: str) -> None:
    """Test Server with data generation enabled."""
    server = Server(models_file, generate_data=True, data_count=5)

    assert server.generate_data is True
    assert server.data_count == 5


# =============================================================================
# TESTS: App Creation
# =============================================================================


def test_create_app_returns_fastapi(server: Server) -> None:
    """Test create_app returns FastAPI instance."""
    app = server.create_app()

    assert isinstance(app, FastAPI)
    assert app.title == "Mock API"
    assert app.version == "1.0.0"


def test_create_app_includes_routes(server: Server) -> None:
    """Test create_app includes all generated routes."""
    app = server.create_app()

    # Each model gets 5 routes
    total_models = len(server.schemas)
    expected_routes = total_models * 5

    # Count only API CRUD routes (exclude docs, openapi, etc)
    api_routes = [
        r
        for r in app.routes
        if hasattr(r, "path") and r.path.startswith(server.prefix)  # type: ignore[attr-defined]
    ]
    assert len(api_routes) == expected_routes


def test_create_app_docs_enabled(server: Server) -> None:
    """Test create_app enables OpenAPI docs."""
    app = server.create_app()

    assert app.docs_url == "/docs"
    assert app.redoc_url == "/redoc"


def test_app_property_lazy_initialization(server: Server) -> None:
    """Test app property creates app on first access."""
    # App not created yet
    assert not server.has_app

    # Access app property
    app = server.app

    # App created and cached
    assert isinstance(app, FastAPI)
    assert server.has_app

    # Second access returns same instance
    app2 = server.app
    assert app2 is app


# =============================================================================
# TESTS: Data Pre-population
# =============================================================================


def test_data_prepopulation_disabled_by_default(server: Server) -> None:
    """Test data is not generated by default."""
    app = server.create_app()
    client = TestClient(app)

    # Check that data is empty
    response = client.get("/api/v1/contacts")
    assert response.status_code == HTTPStatus.OK

    data = response.json()
    assert data["pagination"]["total_items"] == 0


def test_data_prepopulation_when_enabled(models_file: str) -> None:
    """Test data is generated when enabled."""
    server = Server(models_file, generate_data=True, data_count=10)
    app = server.create_app()
    client = TestClient(app)

    # Check that Contact data was generated
    response = client.get("/api/v1/contacts")
    assert response.status_code == HTTPStatus.OK

    data = response.json()
    assert data["pagination"]["total_items"] == 10


def test_data_prepopulation_custom_count(models_file: str) -> None:
    """Test data generation with custom count."""
    server = Server(models_file, generate_data=True, data_count=25)
    app = server.create_app()
    client = TestClient(app)

    # Check that 25 items were generated
    response = client.get("/api/v1/contacts?page_size=100")
    assert response.status_code == HTTPStatus.OK

    data = response.json()
    assert data["pagination"]["total_items"] == 25


def test_data_prepopulation_all_models(models_file: str) -> None:
    """Test data is generated for all models."""
    server = Server(models_file, generate_data=True, data_count=5)
    app = server.create_app()
    client = TestClient(app)

    # Check multiple model endpoints
    endpoints = ["/api/v1/contacts", "/api/v1/authors", "/api/v1/products"]

    for endpoint in endpoints:
        response = client.get(endpoint)
        assert response.status_code == HTTPStatus.OK

        data = response.json()
        assert data["pagination"]["total_items"] == 5


# =============================================================================
# TESTS: Integration with Components
# =============================================================================


def test_server_integrates_parser(server: Server) -> None:
    """Test server correctly integrates SchemaParser."""
    # Parser should have parsed models
    assert len(server.schemas) > 0
    assert "Contact" in server.schemas
    assert "Author" in server.schemas


def test_server_integrates_store(server: Server, client: TestClient) -> None:
    """Test server correctly integrates DataStore."""
    # Create data via API
    payload = {
        "name": "Alice",
        "email": "alice@example.com",
        "phone": "555-1234",
        "username": "alice",
        "first_name": "Alice",
        "last_name": "Smith",
    }

    response = client.post("/api/v1/contacts", json=payload)
    assert response.status_code == HTTPStatus.CREATED

    # Verify data is in store
    assert server.store.count("Contact") == 1


def test_server_integrates_router(server: Server) -> None:
    """Test server correctly integrates RouterGenerator."""
    app = server.create_app()

    # Router should have generated CRUD endpoints
    routes = [r for r in app.routes if hasattr(r, "path")]
    paths = {r.path for r in routes}  # type: ignore[attr-defined]

    # Check key endpoints exist
    assert "/api/v1/contacts" in paths
    assert "/api/v1/contacts/{instance_id}" in paths
    assert "/api/v1/authors" in paths


# =============================================================================
# TESTS: CRUD Operations via Server
# =============================================================================


def test_server_crud_create(client: TestClient) -> None:
    """Test create operation via server."""
    payload = {
        "name": "Bob",
        "email": "bob@example.com",
        "phone": "555-5678",
        "username": "bob",
        "first_name": "Bob",
        "last_name": "Jones",
    }

    response = client.post("/api/v1/contacts", json=payload)

    assert response.status_code == HTTPStatus.CREATED
    data = response.json()
    assert data["name"] == "Bob"
    assert data["id"] == 1


def test_server_crud_read(client: TestClient, server: Server) -> None:
    """Test read operation via server."""
    # Create data
    created = server.store.create(
        "Contact",
        {
            "name": "Alice",
            "email": "alice@example.com",
            "phone": "555-1234",
            "username": "alice",
            "first_name": "Alice",
            "last_name": "Smith",
        },
    )

    # Read via API
    response = client.get(f"/api/v1/contacts/{created['id']}")

    assert response.status_code == HTTPStatus.OK
    data = response.json()
    assert data["id"] == created["id"]
    assert data["name"] == "Alice"


def test_server_crud_update(client: TestClient, server: Server) -> None:
    """Test update operation via server."""
    # Create data
    created = server.store.create(
        "Contact",
        {
            "name": "Alice",
            "email": "alice@example.com",
            "phone": "555-1234",
            "username": "alice",
            "first_name": "Alice",
            "last_name": "Smith",
        },
    )

    # Update via API
    payload = {
        "name": "Alice Updated",
        "email": "alice.updated@example.com",
        "phone": "555-9999",
        "username": "alice_updated",
        "first_name": "Alice",
        "last_name": "Updated",
    }

    response = client.put(f"/api/v1/contacts/{created['id']}", json=payload)

    assert response.status_code == HTTPStatus.OK
    data = response.json()
    assert data["name"] == "Alice Updated"


def test_server_crud_delete(client: TestClient, server: Server) -> None:
    """Test delete operation via server."""
    # Create data
    created = server.store.create(
        "Contact",
        {
            "name": "Alice",
            "email": "alice@example.com",
            "phone": "555-1234",
            "username": "alice",
            "first_name": "Alice",
            "last_name": "Smith",
        },
    )

    # Delete via API
    response = client.delete(f"/api/v1/contacts/{created['id']}")

    assert response.status_code == HTTPStatus.NO_CONTENT

    # Verify deletion
    assert server.store.count("Contact") == 0


def test_server_crud_list(client: TestClient, server: Server) -> None:
    """Test list operation via server."""
    # Create multiple items
    for i in range(5):
        server.store.create(
            "Contact",
            {
                "name": f"User {i}",
                "email": f"user{i}@example.com",
                "phone": f"555-{i:04d}",
                "username": f"user{i}",
                "first_name": "User",
                "last_name": f"{i}",
            },
        )

    # List via API
    response = client.get("/api/v1/contacts")

    assert response.status_code == HTTPStatus.OK
    data = response.json()
    assert len(data["items"]) == 5
    assert data["pagination"]["total_items"] == 5


# =============================================================================
# TESTS: Edge Cases
# =============================================================================


def test_server_with_nonexistent_file() -> None:
    """Test Server with nonexistent models file raises error."""
    with pytest.raises(SchemaFileNotFoundError):
        Server("/nonexistent/path/models.py")


def test_server_multiple_app_creation(server: Server) -> None:
    """Test creating app multiple times."""
    app1 = server.create_app()
    app2 = server.create_app()

    # Each call creates a new app instance
    assert app1 is not app2

    # But app property returns the last created instance
    assert server.app is app2
