"""Faker-based data generator implementation."""

from __future__ import annotations

import random
from datetime import date, datetime
from typing import Any

from faker import Faker

from mock_api.core.exceptions.generation import GenerationError
from mock_api.domain.generation.protocols import (
    IDataGenerator,
    IFieldGenerationStrategy,
)
from mock_api.domain.value_objects.schema import FieldSchema, ModelSchema


class FakerDataGenerator(IDataGenerator):
    """Generate realistic fake data using Faker library.

    Follows Faker best practices:
    - Single Faker instance per generator
    - Seed set once at initialization
    - Simple type-based generation
    """

    def __init__(
        self,
        schemas: dict[str, ModelSchema],
        *,
        locale: str | None = None,
        seed: int | None = None,
    ) -> None:
        """Initialize generator.

        Args:
            schemas: Model schemas (for protocol compliance)
            locale: Faker locale (default: en_US)
            seed: Random seed for reproducibility
        """
        self._schemas = schemas  # Store for future use
        self._faker = Faker(locale or "en_US")

        if seed is not None:
            Faker.seed(seed)
            random.seed(seed)

    def generate(
        self,
        schema: ModelSchema,
        count: int = 10,
        *,
        locale: str | None = None,
        seed: int | None = None,
    ) -> list[dict[str, Any]]:
        """Generate fake entities.

        Args:
            schema: Model schema
            count: Number of entities to generate
            locale: Override locale (currently unused, uses instance locale)
            seed: Override seed (currently unused, uses instance seed)

        Returns:
            List of entity dicts without primary keys

        Raises:
            GenerationError: If generation fails
        """
        # Store for potential future use
        _ = locale, seed

        try:
            return [self._generate_entity(schema, count) for _ in range(count)]
        except Exception as e:
            raise GenerationError(
                message=f"Failed to generate data for {schema.name}",
                details={"model": schema.name, "error": str(e)},
            ) from e

    def generate_field_value(
        self,
        field: FieldSchema,
        *,
        locale: str | None = None,
    ) -> Any:
        """Generate single field value.

        Args:
            field: Field schema
            locale: Override locale (currently unused, uses instance locale)

        Returns:
            Generated value
        """
        _ = locale  # Store for potential future use
        return self._generate_field(field, max_fk_id=100)

    def _generate_entity(self, schema: ModelSchema, max_fk_id: int) -> dict[str, Any]:
        """Generate single entity."""
        entity: dict[str, Any] = {}

        for field in schema.fields:
            # Skip primary key (auto-generated by repository)
            if field.name == schema.primary_key:
                continue

            # Optional fields: 50% None
            if field.is_optional and random.random() < 0.5:
                entity[field.name] = None
                continue

            entity[field.name] = self._generate_field(field, max_fk_id)

        return entity

    def _generate_field(self, field: FieldSchema, max_fk_id: int) -> Any:
        """Generate field value."""
        # Foreign key: random ID
        if field.is_foreign_key:
            return random.randint(1, max_fk_id)

        # Try smart generation by field name
        if hasattr(self._faker, field.name):
            provider = getattr(self._faker, field.name)
            if callable(provider):
                try:
                    return provider()
                except Exception:
                    pass

        # Fallback to type-based generation
        return self._generate_by_type(field.type)

    def register_strategy(self, strategy: IFieldGenerationStrategy) -> None:
        """Register custom field generation strategy.

        Args:
            strategy: Custom generation strategy

        Note:
            Not currently implemented. Reserved for future extensibility.
        """
        _ = strategy  # Store for future use

    def _generate_by_type(self, field_type: type) -> Any:
        """Generate value by type."""
        if field_type is str:
            return self._faker.word()
        if field_type is int:
            return self._faker.random_int(min=1, max=10000)
        if field_type is float:
            return round(random.uniform(0.0, 1000.0), 2)
        if field_type is bool:
            return self._faker.boolean()
        if field_type is date:
            return self._faker.date_object()
        if field_type is datetime:
            return self._faker.date_time()

        # Unknown type: default to string
        return self._faker.word()
